class PlayerControls:
    PLAY = "musicplayer_play"
    STOP = "musicplayer_stop"
    PAUSE = "musicplayer_pause"
    SKIP = "musicplayer_skip"
    SHUFFLE = "musicplayer_shuffle"
    LOOP_MODE = "musicplayer_loop_mode"
    ON_LOOP_MODE = "musicplayer_on_loop_mode"
    BACK = "musicplayer_back"
    VOLUMEM = "musicplayer_volumem"
    VOLUMEP = "musicplayer_volumep"
    PLAYLIST = "musicplayer_playlist"
    BASSBOOST = "musicplayer_bassboost"
    EFFECTS = "musicplayer_effects"